name: GitHub-Profile-3D-Contrib
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Replace Pie Colors
        run: |
          
        # HTML
          sed -i 's/#e34c26/#c85373/g' ./profile-3d-contrib/profile-night-green.svg
        # JavaScript
          sed -i 's/#DA5B0B/#fdd1dd/g' ./profile-3d-contrib/profile-night-green.svg
        # C++
          sed -i 's/#f1e05a/#fb779b/g' ./profile-3d-contrib/profile-night-green.svg
        # CSS
          sed -i 's/#663399/#fca4bc/g' ./profile-3d-contrib/profile-night-green.svg

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi