name: GitHub-Profile-3D-Contrib
on:
  schedule:
    # Runs at 18:00 UTC (1:00 PM EST, 10:00 AM PST, etc.)
    # Change the cron expression if you want a different daily time.
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Replace Pie Colors
        run: |
          sed -i 's/#e34c26/#fed9e3/g' ./profile-3d-contrib/profile-night-green.svg
          sed -i 's/#DA5B0B/#fda7be/g' ./profile-3d-contrib/profile-night-green.svg
          sed -i 's/#f1e05a/#fb759a/g' ./profile-3d-contrib/profile-night-green.svg
          sed -i 's/#663399/#fa4375/g' ./profile-3d-contrib/profile-night-green.svg
        # future colors
          sed -i 's/#f1e05a/#fa4375/g' ./profile-3d-contrib/profile-night-green.svg
          sed -i 's/#f1e05a/#fa4375/g' ./profile-3d-contrib/profile-night-green.svg
          sed -i 's/#f1e05a/#fa4375/g' ./profile-3d-contrib/profile-night-green.svg
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi